tasks:
  - init: |
      cd build && cmake .. && make
    command: |
      gcc -v

vscode:
  extensions:
    - 13xforever.language-x86-64-assembly
#    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
